/**
 * M1 — Admin Command Registry
 * Singleton registry of ≥50 admin commands (navigation + actions).
 * Actions are stubs (filled at runtime by CommandPalette via useNavigate).
 */

export interface Command {
  id: string;
  label: string;
  labelEn?: string;
  description?: string;
  icon?: string;
  category: 'navigation' | 'action' | 'entity' | 'recent';
  keywords?: string[];
  action: () => void;
}

export type CommandDef = Omit<Command, 'action'> & { path?: string };

export const COMMAND_REGISTRY: CommandDef[] = [
  // ── Navigation: 30 admin routes ───────────────────────────────────────────
  {
    id: 'nav-dashboard',
    label: 'Dashboard',
    labelEn: 'Dashboard',
    icon: 'LayoutDashboard',
    category: 'navigation',
    path: '/admin/dashboard',
    keywords: ['ana', 'panel', 'genel', 'overview'],
  },
  {
    id: 'nav-leads',
    label: 'Adaylar',
    labelEn: 'Leads',
    icon: 'UserPlus',
    category: 'navigation',
    path: '/admin/leads',
    keywords: ['aday', 'lead', 'prospect'],
  },
  {
    id: 'nav-deals',
    label: 'Fırsatlar',
    labelEn: 'Deals',
    icon: 'Handshake',
    category: 'navigation',
    path: '/admin/deals',
    keywords: ['deal', 'fırsat', 'satış', 'pipeline'],
  },
  {
    id: 'nav-contacts',
    label: 'Kişiler',
    labelEn: 'Contacts',
    icon: 'Users',
    category: 'navigation',
    path: '/admin/contacts',
    keywords: ['kişi', 'contact', 'müşteri'],
  },
  {
    id: 'nav-bookings',
    label: 'Randevular',
    labelEn: 'Bookings',
    icon: 'Calendar',
    category: 'navigation',
    path: '/admin/bookings',
    keywords: ['randevu', 'booking', 'takvim', 'appointment'],
  },
  {
    id: 'nav-services',
    label: 'Hizmetler',
    labelEn: 'Services',
    icon: 'Briefcase',
    category: 'navigation',
    path: '/admin/services',
    keywords: ['hizmet', 'service'],
  },
  {
    id: 'nav-blog',
    label: 'Blog',
    labelEn: 'Blog',
    icon: 'FileText',
    category: 'navigation',
    path: '/admin/blog',
    keywords: ['blog', 'içerik', 'content', 'yazı'],
  },
  {
    id: 'nav-analytics',
    label: 'Analitik',
    labelEn: 'Analytics',
    icon: 'BarChart3',
    category: 'navigation',
    path: '/admin/analytics',
    keywords: ['analitik', 'analytics', 'istatistik', 'rapor'],
  },
  {
    id: 'nav-audit-log',
    label: 'Denetim Günlüğü',
    labelEn: 'Audit Log',
    icon: 'ScrollText',
    category: 'navigation',
    path: '/admin/audit-log',
    keywords: ['audit', 'log', 'denetim', 'geçmiş'],
  },
  {
    id: 'nav-dsar',
    label: 'DSAR Talepleri',
    labelEn: 'DSAR Requests',
    icon: 'Shield',
    category: 'navigation',
    path: '/admin/dsar',
    keywords: ['dsar', 'veri', 'talep', 'kvkk', 'gdpr'],
  },
  {
    id: 'nav-ropa',
    label: 'ROPA Kaydı',
    labelEn: 'ROPA',
    icon: 'BookOpen',
    category: 'navigation',
    path: '/admin/ropa',
    keywords: ['ropa', 'işleme', 'kayıt', 'gdpr'],
  },
  {
    id: 'nav-breach',
    label: 'İhlal Yönetimi',
    labelEn: 'Breach Management',
    icon: 'AlertTriangle',
    category: 'navigation',
    path: '/admin/breach',
    keywords: ['ihlal', 'breach', 'güvenlik', 'incident'],
  },
  {
    id: 'nav-consent-ledger',
    label: 'Rıza Defteri',
    labelEn: 'Consent Ledger',
    icon: 'ClipboardCheck',
    category: 'navigation',
    path: '/admin/consent-ledger',
    keywords: ['rıza', 'consent', 'kvkk', 'gdpr'],
  },
  {
    id: 'nav-rbac',
    label: 'Rol & İzin Yönetimi',
    labelEn: 'RBAC',
    icon: 'Lock',
    category: 'navigation',
    path: '/admin/rbac',
    keywords: ['rbac', 'rol', 'izin', 'yetki', 'role', 'permission'],
  },
  {
    id: 'nav-users',
    label: 'Kullanıcılar',
    labelEn: 'Users',
    icon: 'Users2',
    category: 'navigation',
    path: '/admin/users',
    keywords: ['kullanıcı', 'user', 'hesap'],
  },
  {
    id: 'nav-settings',
    label: 'Ayarlar',
    labelEn: 'Settings',
    icon: 'Settings',
    category: 'navigation',
    path: '/admin/settings',
    keywords: ['ayar', 'settings', 'config', 'yapılandırma'],
  },
  {
    id: 'nav-security',
    label: 'Güvenlik',
    labelEn: 'Security',
    icon: 'ShieldCheck',
    category: 'navigation',
    path: '/admin/security',
    keywords: ['güvenlik', 'security', '2fa', 'mfa'],
  },
  {
    id: 'nav-ai-page',
    label: 'AI Asistan',
    labelEn: 'AI Page',
    icon: 'Bot',
    category: 'navigation',
    path: '/admin/ai',
    keywords: ['ai', 'asistan', 'yapay zeka', 'ollama'],
  },
  {
    id: 'nav-campaign-wizard',
    label: 'Kampanya Sihirbazı',
    labelEn: 'Campaign Wizard',
    icon: 'Wand2',
    category: 'navigation',
    path: '/admin/campaigns',
    keywords: ['kampanya', 'campaign', 'wizard', 'sihirbaz'],
  },
  {
    id: 'nav-media-library',
    label: 'Medya Kütüphanesi',
    labelEn: 'Media Library',
    icon: 'Image',
    category: 'navigation',
    path: '/admin/media',
    keywords: ['medya', 'media', 'dosya', 'file', 'image', 'görsel'],
  },
  {
    id: 'nav-sessions',
    label: 'Oturumlar',
    labelEn: 'Sessions',
    icon: 'Activity',
    category: 'navigation',
    path: '/admin/sessions',
    keywords: ['oturum', 'session', 'aktif', 'bağlantı'],
  },
  {
    id: 'nav-help',
    label: 'Yardım',
    labelEn: 'Help',
    icon: 'HelpCircle',
    category: 'navigation',
    path: '/admin/help',
    keywords: ['yardım', 'help', 'dokümantasyon', 'docs'],
  },
  {
    id: 'nav-overview',
    label: 'Genel Bakış',
    labelEn: 'Overview',
    icon: 'Eye',
    category: 'navigation',
    path: '/admin/overview',
    keywords: ['genel', 'bakış', 'overview', 'özet'],
  },
  {
    id: 'nav-newsletter',
    label: 'Bülten',
    labelEn: 'Newsletter',
    icon: 'Mail',
    category: 'navigation',
    path: '/admin/newsletter',
    keywords: ['bülten', 'newsletter', 'e-posta', 'email'],
  },
  {
    id: 'nav-crm',
    label: 'CRM',
    labelEn: 'CRM',
    icon: 'Database',
    category: 'navigation',
    path: '/admin/crm',
    keywords: ['crm', 'müşteri', 'ilişki'],
  },
  {
    id: 'nav-collections',
    label: 'Koleksiyonlar',
    labelEn: 'Collections',
    icon: 'FolderOpen',
    category: 'navigation',
    path: '/admin/collections',
    keywords: ['koleksiyon', 'collection', 'içerik'],
  },
  {
    id: 'nav-pages',
    label: 'Sayfalar',
    labelEn: 'Pages',
    icon: 'Layout',
    category: 'navigation',
    path: '/admin/pages',
    keywords: ['sayfa', 'page', 'içerik'],
  },
  {
    id: 'nav-services-edit',
    label: 'Hizmet Düzenle',
    labelEn: 'Services Edit',
    icon: 'PenTool',
    category: 'navigation',
    path: '/admin/services/edit',
    keywords: ['hizmet', 'düzenle', 'edit', 'service'],
  },
  {
    id: 'nav-profile',
    label: 'Profil',
    labelEn: 'Profile',
    icon: 'User',
    category: 'navigation',
    path: '/admin/profile',
    keywords: ['profil', 'profile', 'hesap', 'account'],
  },
  {
    id: 'nav-dev-analytics',
    label: 'Geliştirici Analitik',
    labelEn: 'Dev Analytics',
    icon: 'Code2',
    category: 'navigation',
    path: '/admin/dev-analytics',
    keywords: ['dev', 'geliştirici', 'developer', 'analitik'],
  },

  // ── Actions: 21+ hizmet/action entries ────────────────────────────────────
  {
    id: 'action-new-lead',
    label: 'Yeni Aday Ekle',
    labelEn: 'Add New Lead',
    icon: 'UserPlus',
    category: 'action',
    keywords: ['ekle', 'yeni', 'aday', 'lead', 'add'],
  },
  {
    id: 'action-start-dsar',
    label: 'DSAR Başlat',
    labelEn: 'Initiate DSAR',
    icon: 'ShieldAlert',
    category: 'action',
    keywords: ['dsar', 'başlat', 'veri', 'talep', 'initiate'],
  },
  {
    id: 'action-report-breach',
    label: 'İhlal Bildir',
    labelEn: 'Report Breach',
    icon: 'AlertOctagon',
    category: 'action',
    keywords: ['ihlal', 'bildir', 'breach', 'report', 'güvenlik'],
  },
  {
    id: 'action-download-report',
    label: 'Rapor İndir',
    labelEn: 'Download Report',
    icon: 'Download',
    category: 'action',
    keywords: ['rapor', 'indir', 'download', 'export', 'dışa aktar'],
  },
  {
    id: 'action-new-contact',
    label: 'Yeni Kişi Ekle',
    labelEn: 'Add New Contact',
    icon: 'UserCheck',
    category: 'action',
    keywords: ['kişi', 'ekle', 'yeni', 'contact', 'add'],
  },
  {
    id: 'action-new-booking',
    label: 'Yeni Randevu',
    labelEn: 'New Booking',
    icon: 'CalendarPlus',
    category: 'action',
    keywords: ['randevu', 'yeni', 'booking', 'new'],
  },
  {
    id: 'action-export-contacts',
    label: 'Kişileri Dışa Aktar',
    labelEn: 'Export Contacts',
    icon: 'FileUp',
    category: 'action',
    keywords: ['kişi', 'dışa', 'aktar', 'export', 'csv'],
  },
  {
    id: 'action-send-newsletter',
    label: 'Bülten Gönder',
    labelEn: 'Send Newsletter',
    icon: 'Send',
    category: 'action',
    keywords: ['bülten', 'gönder', 'newsletter', 'send', 'email'],
  },
  {
    id: 'action-new-blog-post',
    label: 'Yeni Blog Yazısı',
    labelEn: 'New Blog Post',
    icon: 'PenSquare',
    category: 'action',
    keywords: ['blog', 'yeni', 'yazı', 'post', 'content'],
  },
  {
    id: 'action-invite-user',
    label: 'Kullanıcı Davet Et',
    labelEn: 'Invite User',
    icon: 'UserCog',
    category: 'action',
    keywords: ['kullanıcı', 'davet', 'invite', 'user'],
  },
  {
    id: 'action-view-logs',
    label: 'Günlükleri Gör',
    labelEn: 'View Logs',
    icon: 'List',
    category: 'action',
    keywords: ['günlük', 'log', 'görüntüle', 'view'],
  },
  {
    id: 'action-refresh-cache',
    label: 'Önbelleği Temizle',
    labelEn: 'Clear Cache',
    icon: 'RefreshCw',
    category: 'action',
    keywords: ['önbellek', 'cache', 'temizle', 'clear', 'refresh'],
  },
  {
    id: 'action-backup',
    label: 'Yedek Al',
    labelEn: 'Create Backup',
    icon: 'HardDrive',
    category: 'action',
    keywords: ['yedek', 'backup', 'veri'],
  },
  {
    id: 'action-change-password',
    label: 'Şifre Değiştir',
    labelEn: 'Change Password',
    icon: 'KeyRound',
    category: 'action',
    keywords: ['şifre', 'parola', 'password', 'değiştir', 'change'],
  },
  {
    id: 'action-enable-2fa',
    label: '2FA Etkinleştir',
    labelEn: 'Enable 2FA',
    icon: 'Smartphone',
    category: 'action',
    keywords: ['2fa', 'iki faktör', 'two-factor', 'güvenlik', 'mfa'],
  },
  {
    id: 'action-archive-lead',
    label: 'Adayı Arşivle',
    labelEn: 'Archive Lead',
    icon: 'Archive',
    category: 'action',
    keywords: ['aday', 'arşiv', 'lead', 'archive'],
  },
  {
    id: 'action-new-deal',
    label: 'Yeni Fırsat Oluştur',
    labelEn: 'Create New Deal',
    icon: 'PlusCircle',
    category: 'action',
    keywords: ['fırsat', 'yeni', 'deal', 'create', 'oluştur'],
  },
  {
    id: 'action-generate-invoice',
    label: 'Fatura Oluştur',
    labelEn: 'Generate Invoice',
    icon: 'Receipt',
    category: 'action',
    keywords: ['fatura', 'invoice', 'oluştur', 'generate'],
  },
  {
    id: 'action-upload-media',
    label: 'Medya Yükle',
    labelEn: 'Upload Media',
    icon: 'Upload',
    category: 'action',
    keywords: ['medya', 'yükle', 'upload', 'dosya', 'file'],
  },
  {
    id: 'action-search-all',
    label: 'Tümünde Ara',
    labelEn: 'Search All',
    icon: 'Search',
    category: 'action',
    keywords: ['ara', 'arama', 'search', 'bul', 'find'],
  },
  {
    id: 'action-open-website',
    label: 'Web Sitesini Aç',
    labelEn: 'Open Website',
    icon: 'Globe',
    category: 'action',
    keywords: ['web', 'site', 'aç', 'open', 'public'],
  },
];
