#!/usr/bin/env bash
# ─── eCyPro Auto-Setup Script ────────────────────────────────────────────────
# Otomatik olarak tüm kripto secret'ları üretir ve .env.local'a yazar.
# Mevcut .env'den bilinen API keylerini kopyalar.
# Kullanım: bash scripts/setup-auto.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
ENV_LOCAL="$ROOT/.env.local"
ENV_MAIN="$ROOT/.env"
ENV_EXAMPLE="$ROOT/.env.example"

GREEN="\033[0;32m"
YELLOW="\033[1;33m"
RED="\033[0;31m"
NC="\033[0m"

log()  { echo -e "${GREEN}[setup]${NC} $1"; }
warn() { echo -e "${YELLOW}[warn]${NC}  $1"; }
err()  { echo -e "${RED}[error]${NC} $1"; }

log "eCyPro Auto-Setup başladı"

# ── 1. Mevcut .env'den key'leri yükle ────────────────────────────────────────
declare -A EXISTING_KEYS

load_env_file() {
  local file="$1"
  if [[ -f "$file" ]]; then
    while IFS= read -r line || [[ -n "$line" ]]; do
      [[ "$line" =~ ^#.*$ || -z "$line" ]] && continue
      key="${line%%=*}"
      val="${line#*=}"
      val="${val%\"}"
      val="${val#\"}"
      EXISTING_KEYS["$key"]="$val"
    done < "$file"
  fi
}

load_env_file "$ENV_MAIN"
load_env_file "$ENV_LOCAL"

# ── 2. Kripto secret'ları üret (yoksa) ───────────────────────────────────────
generate_secret() {
  local key="$1"
  local len="${2:-32}"
  if [[ -n "${EXISTING_KEYS[$key]}" && "${EXISTING_KEYS[$key]}" != "" ]]; then
    echo "${EXISTING_KEYS[$key]}"
  else
    openssl rand -hex "$len"
  fi
}

INDEXNOW_KEY=$(generate_secret "INDEXNOW_KEY" 16)
BOOKING_HMAC=$(generate_secret "BOOKING_HMAC_SECRET" 32)
TOTP_KEY=$(generate_secret "TOTP_ENCRYPTION_KEY" 32)
JWT_SECRET=$(generate_secret "JWT_SECRET" 32)

if [[ "$JWT_SECRET" == "change_me_local_only_minimum_32_chars_aaaaaa" || "$JWT_SECRET" == "change-this-to-a-long-random-string-in-production" ]]; then
  JWT_SECRET=$(openssl rand -hex 32)
fi

# ── 3. IndexNow doğrulama dosyasını oluştur ───────────────────────────────────
INDEXNOW_FILE="$ROOT/public/${INDEXNOW_KEY}.txt"
if [[ ! -f "$INDEXNOW_FILE" ]]; then
  echo "$INDEXNOW_KEY" > "$INDEXNOW_FILE"
  log "IndexNow doğrulama dosyası: public/${INDEXNOW_KEY}.txt"
fi

# ── 4. Mevcut API keylerini al ────────────────────────────────────────────────
PEXELS_KEY="${EXISTING_KEYS[PEXELS_API_KEY]:-}"
OPENAI_KEY="${EXISTING_KEYS[OPENAI_API_KEY]:-}"
OPENAI_BASE="${EXISTING_KEYS[OPENAI_BASE_URL]:-https://openrouter.ai/api/v1}"
OPENAI_MODEL="${EXISTING_KEYS[OPENAI_MODEL]:-openai/gpt-4o-mini}"
GEMINI_KEY="${EXISTING_KEYS[GEMINI_API_KEY]:-}"
GOOGLE_KEY="${EXISTING_KEYS[GOOGLE_API_KEY]:-}"
TELEGRAM_TOKEN="${EXISTING_KEYS[TELEGRAM_BOT_TOKEN]:-}"
TUNNEL_TOKEN="${EXISTING_KEYS[TUNNEL_TOKEN]:-}"
CAL_WEBHOOK="${EXISTING_KEYS[CAL_COM_WEBHOOK_SECRET]:-}"
CAL_USERNAME="${EXISTING_KEYS[CAL_COM_USERNAME]:-}"
DB_URL="${EXISTING_KEYS[DATABASE_URL]:-postgresql://ecypro:ecypro@localhost:5433/ecypro?schema=public}"
SENTRY_DSN="${EXISTING_KEYS[SENTRY_DSN]:-}"
VITE_SENTRY_DSN="${EXISTING_KEYS[VITE_SENTRY_DSN]:-}"
LOGTAIL_TOKEN="${EXISTING_KEYS[LOGTAIL_SOURCE_TOKEN]:-}"
RESEND_KEY="${EXISTING_KEYS[RESEND_API_KEY]:-}"
GA_ID="${EXISTING_KEYS[VITE_GA_TRACKING_ID]:-}"

# ── 5. .env.local yaz ────────────────────────────────────────────────────────
cat > "$ENV_LOCAL" << ENVEOF
# ─── eCyPro .env.local ── Auto-generated by scripts/setup-auto.sh ───────────
# gitignored. GERÇEK KEY'LER BURADA. .env.example'a koyma.

# ─── Kripto Secrets ───────────────────────────────────────────────────────────
JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=7d
BOOKING_HMAC_SECRET=${BOOKING_HMAC}
TOTP_ENCRYPTION_KEY=${TOTP_KEY}
INDEXNOW_KEY=${INDEXNOW_KEY}

# ─── Database ─────────────────────────────────────────────────────────────────
DATABASE_URL=${DB_URL}

# ─── Server ───────────────────────────────────────────────────────────────────
PORT=3001
NODE_ENV=development
CORS_ORIGIN=http://localhost:5173,http://localhost:4173,http://localhost:3000
TRUST_PROXY=1
LOG_LEVEL=info

# ─── Frontend ─────────────────────────────────────────────────────────────────
VITE_API_URL=http://localhost:3001/api
VITE_PROD_URL=https://www.ecypro.com

# ─── Redis (opsiyonel) ────────────────────────────────────────────────────────
REDIS_URL=redis://localhost:6379

# ─── AI APIs ──────────────────────────────────────────────────────────────────
OPENAI_API_KEY=${OPENAI_KEY}
OPENAI_BASE_URL=${OPENAI_BASE}
OPENAI_MODEL=${OPENAI_MODEL}
GEMINI_API_KEY=${GEMINI_KEY}
GOOGLE_API_KEY=${GOOGLE_KEY}

# Ollama (local)
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_DEFAULT_MODEL=qwen2.5-coder:14b
OLLAMA_TEMPERATURE=0.2
VITE_OLLAMA_BASE_URL=http://localhost:11434

# ─── Content Generation ───────────────────────────────────────────────────────
PEXELS_API_KEY=${PEXELS_KEY}

# ─── Telegram ─────────────────────────────────────────────────────────────────
TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}
VITE_TELEGRAM_BOT_TOKEN=${TELEGRAM_TOKEN}

# ─── Cloudflare Tunnel ────────────────────────────────────────────────────────
TUNNEL_TOKEN=${TUNNEL_TOKEN}

# ─── Cal.com ──────────────────────────────────────────────────────────────────
CAL_COM_API_KEY=
CAL_COM_EVENT_TYPE_ID=
CAL_COM_USERNAME=${CAL_USERNAME}
CAL_COM_WEBHOOK_SECRET=${CAL_WEBHOOK}

# ─── Email (Resend) ───────────────────────────────────────────────────────────
RESEND_API_KEY=${RESEND_KEY}
EMAIL_FROM=eCyPro <noreply@ecypro.com>
EMAIL_FROM_ADDRESS=noreply@ecypro.com

# ─── Error Reporting ──────────────────────────────────────────────────────────
SENTRY_DSN=${SENTRY_DSN}
VITE_SENTRY_DSN=${VITE_SENTRY_DSN}

# ─── Analytics ────────────────────────────────────────────────────────────────
VITE_GA_TRACKING_ID=${GA_ID}

# ─── Better Stack (Logtail) ───────────────────────────────────────────────────
LOGTAIL_SOURCE_TOKEN=${LOGTAIL_TOKEN}

# ─── Sentry CI (GitHub Secrets'a ekle) ───────────────────────────────────────
SENTRY_AUTH_TOKEN=
SENTRY_ORG=ecypro
SENTRY_PROJECT=ecypro-frontend

# ─── Google Indexing API ──────────────────────────────────────────────────────
GOOGLE_INDEXING_KEY_PATH=./secrets/indexing-key.json
ENVEOF

log ".env.local güncellendi ✅"
log "IndexNow key: ${INDEXNOW_KEY}"
log "JWT_SECRET: yeni üretildi"
log "BOOKING_HMAC_SECRET: yeni üretildi"

# ── 6. Özet ──────────────────────────────────────────────────────────────────
echo ""
echo "─────────────────────────────────────────────────────────"
echo " eCyPro Setup Özeti"
echo "─────────────────────────────────────────────────────────"
echo " ✅ .env.local yazıldı (kripto secrets + mevcut keys)"
echo " ✅ public/${INDEXNOW_KEY}.txt (IndexNow doğrulama)"
echo ""
echo " ⚠️  Manuel tamamlanması gerekenler:"
[[ -z "$RESEND_KEY" ]]    && echo "   • RESEND_API_KEY     → resend.com"
[[ -z "$GA_ID" ]]          && echo "   • VITE_GA_TRACKING_ID→ analytics.google.com"
[[ -z "${EXISTING_KEYS[CAL_COM_API_KEY]:-}" ]] && echo "   • CAL_COM_API_KEY    → cal.com/settings"
[[ -z "$LOGTAIL_TOKEN" ]]  && echo "   • LOGTAIL_SOURCE_TOKEN → betterstack.com"
echo "─────────────────────────────────────────────────────────"
