import React, { useState } from 'react';
import { FileText, PlusCircle, ExternalLink, Clock, Tag, Loader2, Pencil } from 'lucide-react';
import { motion, AnimatePresence } from 'motion/react';
import { useReducedMotion } from 'motion/react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { apiClient } from '@/lib/api';

// Blog post metadata derived from constants_generated.ts at build time
// Runtime: imported from src/data/blog-posts.json (generated by gen:blog)
interface BlogPostMeta {
  slug: string;
  title: string;
  date: string;
  category: string;
  readTime: string;
  excerpt: string;
}

// Lazy-load blog posts from generated JSON
async function loadBlogPosts(): Promise<BlogPostMeta[]> {
  try {
    const raw = await import('../../data/blog-posts.json', { assert: { type: 'json' } });
    // Map blog-posts.json fields to BlogPostMeta (readingTime → readTime).
    // P14 — was `any[]`; tightened to a structural record with safe optional fields.
    type RawPost = {
      slug?: string;
      title?: string;
      date?: string;
      category?: string;
      readTime?: string;
      readingTime?: string;
      excerpt?: string;
    };
    const items = (raw.default ?? []) as RawPost[];
    return items.map((p) => ({
      slug: p.slug ?? '',
      title: p.title ?? '',
      date: p.date ?? '',
      category: p.category ?? '',
      readTime: p.readTime ?? p.readingTime ?? '5 min',
      excerpt: p.excerpt ?? '',
    }));
  } catch {
    return [];
  }
}

export const AdminBlogPage: React.FC = () => {
  const [posts, setPosts] = useState<BlogPostMeta[]>([]);
  const [loaded, setLoaded] = useState(false);
  const [creating, setCreating] = useState(false);
  const [newTitle, setNewTitle] = useState('');
  const [newSlug, setNewSlug] = useState('');
  const prefersReduced = useReducedMotion();
  const queryClient = useQueryClient();

  const createMutation = useMutation({
    mutationFn: ({ slug, title }: { slug: string; title: string }) =>
      apiClient.post('/admin/blog', { slug, title }),
    onSuccess: () => {
      toast.success('Yazınız oluşturuldu. MDX dosyası sunucuya kaydedildi.');
      setCreating(false);
      setNewTitle('');
      setNewSlug('');
      void queryClient.invalidateQueries({ queryKey: ['admin', 'blog'] });
    },
    onError: () => {
      toast.error('Yazınız oluşturulamadı, lütfen tekrar deneyin.');
    },
  });

  // Load on mount
  React.useEffect(() => {
    loadBlogPosts().then((p) => {
      setPosts(p);
      setLoaded(true);
    });
  }, []);

  const handleSlugify = (title: string) => {
    return title
      .toLowerCase()
      .replace(/ğ/g, 'g')
      .replace(/ü/g, 'u')
      .replace(/ş/g, 's')
      .replace(/ı/g, 'i')
      .replace(/ö/g, 'o')
      .replace(/ç/g, 'c')
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim();
  };

  const handleTitleChange = (t: string) => {
    setNewTitle(t);
    setNewSlug(handleSlugify(t));
  };

  const handleCreate = () => {
    if (!newSlug || createMutation.isPending) return;
    createMutation.mutate({ slug: newSlug, title: newTitle });
  };

  const MotionDiv = prefersReduced ? React.Fragment : motion.div;

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-white flex items-center gap-3">
            <FileText className="text-secondary" size={24} />
            Blog Content
          </h1>
          <p className="text-slate-400 text-sm mt-1">
            {loaded ? `${posts.length} posts` : 'Loading…'} · MDX-based content management
          </p>
        </div>
        <button
          type="button"
          onClick={() => setCreating(true)}
          className="flex items-center gap-2 px-4 py-2.5 bg-secondary text-white rounded-xl font-medium text-sm hover:bg-blue-600 transition-colors"
        >
          <PlusCircle size={14} /> New Post
        </button>
      </div>

      {/* New post form */}
      <AnimatePresence>
        {creating && (
          <motion.div
            initial={prefersReduced ? undefined : { opacity: 0, height: 0 }}
            animate={prefersReduced ? undefined : { opacity: 1, height: 'auto' }}
            exit={prefersReduced ? undefined : { opacity: 0, height: 0 }}
            className="bg-white/3 border border-white/5 rounded-2xl p-6 space-y-4 overflow-hidden"
          >
            <h3 className="text-white font-semibold">New Blog Post</h3>
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label htmlFor="blog-post-title" className="text-xs text-slate-400 mb-1.5 block">
                  Post Title
                </label>
                <input
                  id="blog-post-title"
                  type="text"
                  value={newTitle}
                  onChange={(e) => handleTitleChange(e.target.value)}
                  placeholder="Yapay Zeka ve İş Dünyası"
                  className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-white text-sm outline-none focus:border-secondary/50"
                />
              </div>
              <div>
                <label htmlFor="blog-post-slug" className="text-xs text-slate-400 mb-1.5 block">
                  Slug (auto)
                </label>
                <input
                  id="blog-post-slug"
                  type="text"
                  value={newSlug}
                  onChange={(e) => setNewSlug(e.target.value)}
                  placeholder="yapay-zeka-ve-is-dunyasi"
                  className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-slate-300 text-sm font-mono outline-none focus:border-secondary/50"
                />
              </div>
            </div>
            <div className="flex gap-3 justify-end">
              <button
                type="button"
                onClick={() => setCreating(false)}
                className="px-4 py-2 text-sm text-slate-400 hover:text-white transition-colors"
              >
                Cancel
              </button>
              <button
                type="button"
                onClick={handleCreate}
                disabled={!newSlug || createMutation.isPending}
                aria-busy={createMutation.isPending}
                className="flex items-center gap-2 px-4 py-2 bg-secondary text-white rounded-lg text-sm font-medium hover:bg-blue-600 transition-colors disabled:opacity-50"
              >
                {createMutation.isPending ? (
                  <>
                    <Loader2 size={13} className="animate-spin" aria-hidden="true" /> Kaydediliyor…
                  </>
                ) : (
                  <>
                    <PlusCircle size={13} /> Create Post
                  </>
                )}
              </button>
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Posts list */}
      <div className="space-y-2">
        {!loaded && (
          <div className="flex items-center justify-center py-12 text-slate-400">
            <Loader2 size={20} className="animate-spin mr-2" aria-hidden="true" /> Loading posts…
          </div>
        )}

        {loaded && posts.length === 0 && (
          <div className="text-center py-12 text-slate-400 text-sm">
            No blog posts found. Run{' '}
            <code className="mx-1 bg-white/10 px-1.5 py-0.5 rounded text-xs font-mono">
              npm run gen:blog
            </code>{' '}
            to index your MDX files.
          </div>
        )}

        {posts.map((post, i) => (
          <MotionDiv
            key={post.slug}
            {...(!prefersReduced
              ? {
                  initial: { opacity: 0, y: 8 },
                  animate: { opacity: 1, y: 0 },
                  transition: { delay: i * 0.04 },
                }
              : {})}
          >
            <div className="bg-white/3 border border-white/5 rounded-xl p-4 hover:bg-white/5 transition-colors flex items-start gap-4">
              <div className="flex-1 min-w-0">
                <div className="flex items-center gap-2 mb-1">
                  <span className="text-xs px-2 py-0.5 rounded-full bg-secondary/10 text-secondary font-medium">
                    {post.category}
                  </span>
                  <span className="text-xs text-slate-500 flex items-center gap-1">
                    <Clock size={10} /> {post.readTime}
                  </span>
                </div>
                <h3 className="text-white font-medium text-sm leading-snug">{post.title}</h3>
                <p className="text-slate-400 text-xs mt-1 line-clamp-1">{post.excerpt}</p>
                <div className="flex items-center gap-2 mt-1.5">
                  <Tag size={9} className="text-slate-600" />
                  <span className="text-xs text-slate-500 font-mono">{post.slug}</span>
                  <span className="text-slate-600">·</span>
                  <span className="text-xs text-slate-500">{post.date}</span>
                </div>
              </div>
              <div className="flex items-center gap-1 shrink-0">
                <a
                  href={`/keystatic/collection/posts/item/${post.slug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="p-2 rounded-lg text-slate-500 hover:text-amber-400 hover:bg-amber-400/10 transition-colors"
                  title="Edit in Keystatic"
                >
                  <Pencil size={14} />
                </a>
                <a
                  href={`/blog/${post.slug}`}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="p-2 rounded-lg text-slate-500 hover:text-secondary hover:bg-secondary/10 transition-colors"
                  title="View post"
                >
                  <ExternalLink size={14} />
                </a>
              </div>
            </div>
          </MotionDiv>
        ))}
      </div>

      {/* Info block */}
      {loaded && posts.length > 0 && (
        <div className="bg-slate-800/30 border border-white/5 rounded-xl p-4 text-xs text-slate-400">
          <strong className="text-slate-300">MDX Workflow:</strong>{' '}
          <a
            href="/keystatic"
            target="_blank"
            rel="noopener noreferrer"
            className="text-secondary hover:underline font-medium"
          >
            Keystatic CMS
          </a>{' '}
          → edit in browser → auto-saves to{' '}
          <code className="bg-white/10 px-1 rounded font-mono">src/content/blog/</code> → run{' '}
          <code className="bg-white/10 px-1 rounded font-mono">npm run gen:blog</code> → commit.
        </div>
      )}
    </div>
  );
};
